### ISSUE TITLE
Use Game Server API

### ISSUE THREAD

**Issue by MasterCash** [siggame/TheArena#3]
Switch to using the Game Server API to tell how games are going and to get results.
http://siggame.io/Cerveau/

**Comment by SethKitchen** [comment]
Go to HTTP.cs and look how the post is done for the webserver currently. May need to rename that to WebServerHTTPPost or something


Then go to http://siggame.io/Cerveau then under Setup write a new function called GameServerHTTPPost and write the gameName, session, gameSettings, and playername.

**Comment by SethKitchen** [comment]
Yay Setup is done -- Now for challenge yourself and do the Status -- and then issue will be complete
